theme: jekyll-theme-minimal
baseurl: /cantors-attic
# source: docs
plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll/scholar
optional_front_matter:
  remove_originals: true
defaults:
  - values:
      toc: true
scholar:
  # bibtex_filters: []