theme: jekyll-theme-minimal
baseurl: /cantors-attic
# source: docs
plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-redirect-from
optional_front_matter:
  remove_originals: true
defaults:
  - values:
      toc: true
      
# defaults:
#   - values:
#       layout: "default"
#   - scope:
#       path: "assets/img"
#     values:
#       image: true