theme: jekyll-theme-minimal
# source: docs
plugins:
  - jekyll-default-layout

# defaults:
#   - values:
#       layout: "default"
#   - scope:
#       path: "assets/img"
#     values:
#       image: true